/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KarirRouteImport } from './routes/karir'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as JadwalTokenRouteImport } from './routes/jadwal/$token'
import { Route as KuisTokenRouteImport } from './routes/kuis/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KarirRoute = KarirRouteImport.update({
  id: '/karir',
  path: '/karir',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalTokenRoute = JadwalTokenRouteImport.update({
  id: '/jadwal/$token',
  path: '/jadwal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const KuisTokenRoute = KuisTokenRouteImport.update({
  id: '/kuis/$token',
  path: '/kuis/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/karir': typeof KarirRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jadwal/$token': typeof JadwalTokenRoute
  '/kuis/$token': typeof KuisTokenRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/karir': typeof KarirRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jadwal/$token': typeof JadwalTokenRoute
  '/kuis/$token': typeof KuisTokenRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/karir': typeof KarirRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/jadwal/$token': typeof JadwalTokenRoute
  '/kuis/$token': typeof KuisTokenRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/karir'
    | '/blog/$slug'
    | '/jadwal/$token'
    | '/kuis/$token'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/karir' | '/blog/$slug' | '/jadwal/$token' | '/kuis/$token' | '/blog'
  id:
    | '__root__'
    | '/'
    | '/karir'
    | '/blog/$slug'
    | '/jadwal/$token'
    | '/kuis/$token'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KarirRoute: typeof KarirRoute
  BlogSlugRoute: typeof BlogSlugRoute
  JadwalTokenRoute: typeof JadwalTokenRoute
  KuisTokenRoute: typeof KuisTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karir': {
      id: '/karir'
      path: '/karir'
      fullPath: '/karir'
      preLoaderRoute: typeof KarirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal/$token': {
      id: '/jadwal/$token'
      path: '/jadwal/$token'
      fullPath: '/jadwal/$token'
      preLoaderRoute: typeof JadwalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuis/$token': {
      id: '/kuis/$token'
      path: '/kuis/$token'
      fullPath: '/kuis/$token'
      preLoaderRoute: typeof KuisTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KarirRoute: KarirRoute,
  BlogSlugRoute: BlogSlugRoute,
  JadwalTokenRoute: JadwalTokenRoute,
  KuisTokenRoute: KuisTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
